### ISSUE TITLE
$VirtualServerPartition parameter unused

### ISSUE THREAD

**Issue by jmelosegui** [joel74/POSH-LTM-Rest#121]
Is there any plans to use the following parameter?

[$VirtualServerPartition](https://github.com/joel74/POSH-LTM-Rest/blob/693ef0ab48ca648f927b9c9f3e5c05eecb5c76bb/F5-LTM/Public/Add-iRuleToVirtualServer.ps1#L20)

I cannot see the need for that. 

Could you give me some insights?

Thanks for this awesome project!!!

**Comment by vercellone** [comment]
It appears redundant.  This param should be removed and VirtualServerPartition added as an alias for Partition so that it is a backwards compatible, non-breaking change.

**Comment by joel74** [comment]
I agree it does look like this param is extraneous. However, my vote would be to remove it instead of making it an alias. By turning it into an alias, we're taking something that is currently accepted but has no effect on the outcome, and turning it into something that does have an effect. Also, we currently accept both the Partition and the VirtualServerPartition params, but making VirtualServerPartition an alias for Partition would cause an error to be thrown if both are passed in.  Since we're potentially breaking/changing things no matter how we change them, let's avoid adding to the clutter and remove the extraneous param. A good argument might persuade me otherwise, but I'm currently in favor of removal.

**Comment by vercellone** [comment]
I had considered that an error would be thrown if both are passed in, but felt it would serve as a helpful hint.  However, you make a good point regarding it being a breaking change either way.  No argument from me.

**Comment by joel74** [comment]
PR created.
