### ISSUE TITLE
Support for PowerShell 6

### ISSUE THREAD

**Issue by elijahgagne** [joel74/POSH-LTM-Rest#155]
I'd like to propose adding support for PowerShell 6. In the long term, it certainly seems like a good thing. In the short term, it would provide a way for folks on Mac or Linux to use this module. In my organization, the vast majority of people who manage the F5s are Mac users. In addition, we've been exploring a lot of automation lately, and most of the automation is Linux-based. 

I have created a local branch with some minor changes (https://github.com/joel74/POSH-LTM-Rest/compare/master...elijahgagne:ps6). Those changes are working for me on Windows with both PowerShell 5 and 6. Would you want to test these changes to see if they are working for you?

**Comment by joel74** [comment]
Hi, Elijah,
Absolutely I'd like to test on PS6. Did you test using SkipCertificateCheck on < PS6, out of curiosity? Maybe that works just as well as overriding validation? I'll check that out. With your changes, how far were you able to get in testing with PS6?
Cheers,
Joel

**Comment by elijahgagne** [comment]
Unfortunately PSVersion < 6 does not support `-SkipCertificateCheck` ([MS Doc](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-5.1), change PS version in upper left)

I tested maybe 30% of the functions with PS6 and they all worked. I'm now using PS6 100% of the time and I'll be testing more as needs arise. I'd be surprised if any don't work. I'm also pretty confident that this is not a breaking change for PS5. I'm hopeful that this is non-breaking for PS3 and PS4, but I have not attempted to test those. I see [Microsoft.PowerShell.Commands.BasicHtmlWebResponseObject](https://msdn.microsoft.com/en-us/library/microsoft.powershell.commands.basichtmlwebresponseobject_members(v=vs.85).aspx) was introduced in PS3, so I'd expect that to be fine. 

The last thing to mention is that I'm not sure why HtmlWebResponseObject was being used so I'm not sure what the ramifications of changing to BasicHtmlWebResponseObject are. HtmlWebResponseObject doesn't seem to exist in PS6 so that's why I made the change.

**Comment by joel74** [comment]
I have no idea why we would have chosen to use BasicHtmlWebResponseObject vs HtmlWebResponseObject. Both were introduced in PS3 and both work find with this module on a box using PS3. BasicHtmlWebResponseObject is specifically for parsing a DOM, which we don't need since we always treat the responses from Invoke-RestMethodOverride and Invoke-F5RestMethod as JSON. 

For the SkipCertificateCheck, I'd recommend changing that from gt 5 to ge 6. SkipCertificateCheck isn't available in 5.1.

Given that small tweak, I'm fine with merging your changes in, if you want to make a pull request. Just let me know. Cheers.

**Comment by vercellone** [comment]
Looks like it was something I included in my initial commit, probably _borrowed_ from elsewhere.  Sorry for any inconvenience.
