### ISSUE TITLE
Set-VirtualServer -ProfileNames Overwrites profiles 

### ISSUE THREAD

**Issue by kleinsmk** [joel74/POSH-LTM-Rest#158]
It would appear that Set-VirtualServer  -ProfileNames  overwrites profiles instead of appending them.  Is there an option for this or would this be something I would need to grab then append myself.  Running version  12.1.3.1 .

**Comment by joel74** [comment]
I verified that, even though we're using the Patch method in Set-VirtualServer, it is overwriting the profiles subcollection. I'm guessing it would work the same for the policies subcollection as well. I'm thinking, though, that this is the desired behavior, because otherwise there is not straightforward way to remove profiles (or policies) from a virtual server.

All that said, it does not appear that we currently return the profiles and policies as properties of the Get-VirtualServer call - only references to them. I think it would be helpful to update Get-VirtualServer to retrieve the contents of those reference URLs and return profiles and policies as properties of that call. Otherwise, it's a bit of a pain to get the current ones to append to. I'll look into that.

**Comment by joel74** [comment]
Please review this pull request:
https://github.com/joel74/POSH-LTM-Rest/pull/159

**Comment by kleinsmk** [comment]
Joel, I'm not sure I follow.  Are you suggesting grabbing the existing profile names with the changes made to Get-VirtualServer, then using Set-VirtualServer to apply them all?  Something like $existingProfilefromGetVirtualSever + $myprofile ?

**Comment by joel74** [comment]
Yes, something along those lines. Here's an example:

[Add-NewProfilesToExisting.txt](https://github.com/joel74/POSH-LTM-Rest/files/1826682/Add-NewProfilesToExisting.txt)

**Comment by kleinsmk** [comment]
Thanks a ton.  You practically wrote the whole thing out for me!  Love the module and the support can't be beat.

**Comment by joel74** [comment]
Cheers! Thanks for the kind words. I'm going to leave the pull request out there for a day or so, give other folks a chance to review and comment, and then I'll merge it in. Just fyi, if you choose to grab the contents of the commit and then want to update later.

**Comment by joel74** [comment]
I ran into an issue this afternoon in one of my scripts where I loop through all the iRules in an environment. If I don't pass in a name when I'm calling Get-VirtualServer, I get an error, so I'll need to look into how to handle that scenario.

**Comment by joel74** [comment]
Finally fixed the issue where calling Get-VirtualServer and returning multiple virtual servers, so that the correct profile and policy subcollections are applied to each.
