### ISSUE TITLE
Speed issue

### ISSUE THREAD

**Issue by Crysty1** [joel74/POSH-LTM-Rest#182]
The get-virtualserver is too slow when a large number of virtual servers exist.
Because is only possible to get one virtual server by name, I need to get all virtual servers and search for the specific IP.

Maybe is possible to add ip parameter in order to search by ip with get-virtualserver.

**Comment by joel74** [comment]
Hi, Crysty1, I'd definitely like to help speed things up, but I wonder if adding a destination IP address as a param will help, because the function would still need to look through every virtual server. Since the virtual server name is part of the REST endpoint URL and can be queried directly, it's quick, but I believe one would still need to grab all the virtual servers and then parse them for the destination IP address value you wanted. 

So something like 
`Get-VirtualServer | where {$_.Destination -eq '/Common/10.128.20.215:443' }`
would be as fast as having the function pull back all the virtual servers and then search for the desired IP.

One interesting thing - I find that when I search my own F5, with ~130 virtual servers, it might take 20 to 30 seconds on the first run, and then after that, it completes in 2 or 3 seconds. Kind of strange. How many virtual servers do you need to search through?

Thanks
Joel

**Comment by Crysty1** [comment]
Hi,
I supposed that is a way to get virtual servers by IP in the REST.
I have few partitions but I need to look in all of them and I only have the IP address.
There are about 2500 virtual servers and it takes up to 3 hours to get all (3 to 4.5 seconds for each virtual server). It takes the same time on each run.
An option is to build a map table or store also the virtual servers name. But if I want to check if one IP is used or not, the full server list is needed.
Is a big difference because de F5 xui can display all the virtual servers in 10 seconds.

Thank you

**Comment by joel74** [comment]
Hi,

I asked the question on the devcentral forum and got the answer link [here](https://devcentral.f5.com/questions/use-icontrolrest-to-find-a-virtual-server-by-ip-address-64329): 

I'll experiment with the options offered and maybe you can do the same, and we can compare notes. Thanks.

**Comment by joel74** [comment]
I didn't notice much of a difference when including 'destination' in my request. I wonder if the loop in the code to collect all the subcollection info is causing the performance issue. Please try testing with the included modified version of Get-VirtualServer, which retrieves all virt. servers without expanding the subcollections and see if that improves things. Just rename this, put it in the \Public folder and reimport the module with the -Force flag. Thanks. #
[Get-VirtualServer_ps1.txt](https://github.com/joel74/POSH-LTM-Rest/files/3001175/Get-VirtualServer_ps1.txt)

**Comment by Crysty1** [comment]
Hi,
It's really faster without retrieving subcollections info.
I only need 10 seconds to get all virtual servers. Amazing!
Maybe for the next update, you can consider to add option to get virtual server by IP.
Thank you!

**Comment by joel74** [comment]
Hi, Crysty1, please check out my pull request #185 for this. It provides a flag for excluding the subcollections (and getting the performance increase) and for filtering based on IP address.

**Comment by kleinsmk** [comment]
@Crysty1 

You can roll your own wrapper pretty easily.  Just put the below in a function.  You may need to adjust the $F5Session.WebSession to whatever you are using as your pass-through session variable.  You could even use the default one Joel returns from New-F5Session. 

This is what I use to get a list of all the ips to then determine what the next free IP is for virtual server use.  Sounds like this might be your end use case.

`$uri = $F5Session.BaseURL.Replace('/ltm/','/ltm/virtual?$select=destination')
$obj = Invoke-RestMethodOverride -Method GET -URI $uri -WebSession $F5Session.WebSession`


@joel74 Filtering on the F5 itself is MUCH MUCH faster than doing it on the powershell end I've noticed.  Likely due to the fact that there is a single API call would be my guess.  I've noticed in general the F5 tends to flake out with heavy API usage.  Our sales engineer from F5 hasn't had many suggestions, but I've noticed restarting the java process for the API can speed things back up.

**Comment by joel74** [comment]
@kleinsmk I don't think that filtering by IP on the F5 itself is an option. I asked on devcentral and got [this answer](https://devcentral.f5.com/questions/use-icontrolrest-to-find-a-virtual-server-by-ip-address-64329).

**Comment by halovanic** [comment]
I think there may be another possible solution to this performance issue. I came across a similar problem in Get-PoolMember, where the performance also seemed rather slow for what I believe are the same reasons: needing to loop over all of the subcollection info via subsequent REST requests.

Per the API documentation (I'm not sure how new this is), I found that if I added the `expandSubcollections=true` parameter to the primary request I could parse the subcollections directly from the single larger JSON response.  For cases where we have to go into all subcollections, this does seem to save a significant amount of overhead compared to making hundreds of additional HTTP requests sequentially and the time is noticeably faster.  Perhaps this parameter could be incorporated for cases like these?

Thanks,
Alex

**Comment by SCMoperations** [comment]
I finally got a chance to dig into this a bit! That param does expand the subcollections, so I think you're correct and that using it is the best-performing option. I'm leaving the other code in there for now, and I'll leave the updated code as a pull request for a week or two, to give other interested parties a chance review before merging.

**Comment by joel74** [comment]
Closing with merge of #195 and yes, SCMoperations is also me.
