### ISSUE TITLE
Function renames?

### ISSUE THREAD

**Issue by dsolodow** [joel74/POSH-LTM-Rest#6]
Was reading through the module (planning to add some help blocks) and had a few thoughts on the function names that I wanted to run past you for discussion. If any of these make sense, I'm willing and interested in helping make the necessary updates and changes. :)

**Add-PoolMember**    
**Disable-PoolMember**       
**Disable-PoolMemberForced** - suggest making this a -Force parameter on Disable-PoolMember 
**Enable-PoolMember**        
**Get-AllPoolMembersStatus** 
**Get-CurrentConnections** - suggest using Get-CurrentConnection; convention is that nouns are singular 
**Get-F5session**            
**Get-PoolMember** - would this make more sense as Get-Node ?          
**Get-PoolMemberIP**         
**Get-PoolMembers** - suggest using Get-PoolMember; convention is that nouns are singular           
**Get-PoolMemberStatus**     
**Get-Pools** - suggest using Get-Pool; convention is that nouns are singular                
**Get-PoolsForMember** - Get-NodeMembership ?       
**Get-StatusShape**          
**Remove-PoolMember**        
**Set-PoolMemberDescription**
**Test-F5IsActive** - would this make more sense as Get-F5Status ?

**Comment by joel74** [comment]
Thanks for the suggestions, Damien.

Changing Disable-PoolMemberForced to use Disable-PoolMember with a -Force param makes sense.

Get-CurrentConnections would probably make more sense as Get-CurrentConnectionCount, since it's returning a count and not connections objects.

I'll have to think about the pool member vs. node distinction. I feel that since "pool member" is used pretty ubiquitously / consistently, and that changing one or two functions to use "node" may be confusing, but we can discuss.

Since Get-PoolMembers and Get-Pools return a collection of objects, maybe calling them "Get-PoolMemberCollection" and "Get-PoolCollection" is better? I'm not sure that that's clearer, though. Any other suggestions?

Since Test-F5IsActive returns the status, it does make sense to change that to Get-F5Status.

Cheers,
Joel

**Comment by joel74** [comment]
All function names have been converted to use singular nouns now.
