### ISSUE TITLE
Slow Import-Module Time (greater than 10 minutes) when using powershell 5

### ISSUE THREAD

**Issue by fodonnel** [joel74/POSH-LTM-Rest#76]
I am using powershell V5

The code to Register argument completers  is causing a recursive load of the module.
This results in a load time that is greater than 10 minutes.

I have added the following to the start of F5-LTM.psm1 
    Write-Verbose "$(get-date -f s) Module Load Called"

From that I can see that during the module load, it attempts to recursively load the module again. 

This problem seems to be caused by the Register-ArgumentCompleter  code block in ArgumentCompletion.ps1. I have confirmed my removing that code and testing that the module loads correctly.

I have tried wrapping the Register-ArgumentCompleter code block in a function and calling that as the end of F5-LTM.psm1 but it doesn't fix the problem.

**Comment by vercellone** [comment]
Please provide steps to reproduce.  What is your exact value of $PSVersionTable.PSVersion?  Is the module installed?  From the powershellgallery or from a clone of this repo?  For all users or just the current user?

Also, just to rule it out: Can you try replacing Invoke-NullCoelescing with if..then..else in ArgumentCompletion.ps1 and see if that helps?

**Comment by joel74** [comment]
I'll leave this open till Friday. If we can get steps to repro this, I'll gladly reopen.
Thanks.

**Comment by vercellone** [comment]
I haven't been able to reproduce a 10 minute import.  But, I have been able to reproduce 3-5 minutes.  The root cause seems to be the calls to Get-Command -Module.  This can be alleviated by either hard coding the command names or retrieving them a different way that doesn't require the module to be loaded first.

I have a working draft for which I'll submit a PR later.  Please re-open this issue.

**Comment by fodonnel** [comment]
I am afraid I don't have permission to reopen this issue.

**Comment by joel74** [comment]
Reopened
