### ISSUE TITLE
Auth token shouldn't expire if in use.

### ISSUE THREAD

**Issue by joel74** [joel74/POSH-LTM-Rest#81]
The default life for auth tokens is 20 minutes. It seems strange and undesirable that a token can expire while being actively used. I think we should introduce a means of automatically renewing / regenerating a token when it's being actively used. Test-F5Session seems the natural place to do this check and renewal.

In order to do this automatically, though, we'll need to store the credentials passed in to New-F5Session in the WebSession object. Once we have that, we can check whether the 'Token-Expiration' header is older than the current time. If it is, we'll automatically generate a request for a new token. 

Thoughts?

**Comment by oribe** [comment]
Sounds like a great idea, actually I am running into such issues in a project I'm currently on, the session just expires while it is steel needed.
I think we should regenerate if already expired and even "extend" - regenerate if expiration is within 5 minutes ahead.

In addition, what do you think about adding a session expiration parameter to New-F5Session instead of fixing it to 20 minutes?

**Comment by joel74** [comment]
Hi, oribesser, I'm not sure why the last line of your comment didn't show up here, but I saw you asked about extending the token timeout and making it a param that can be set. I'd looked into that a while back (there's a snippet [here](https://devcentral.f5.com/articles/demystifying-icontrol-rest-part-6-token-based-authentication) of a guy doing it) but I couldn't get it to work and it didn't seem to be a documented feature. It sounds like it merits another look, though.

**Comment by vercellone** [comment]
We should create an internal Invoke-F5RestMethod with an -F5Session param to allow it to handle the logic just in time.

**Comment by joel74** [comment]
I think we can handle this much more simply by adding an optional TokenLifespan param to New-F5Session. I found a post that shows how to do a Patch to change the token expiration, so we can optionally call that if TokenLifespan is passed in.

**Comment by oribesser** [comment]
Are you talking about the post you referenced in your previous comment? He is authenticating to a different URI there (which is also not documented). I also tried it but to no avail.

**Comment by vercellone** [comment]
Based on [How BIG-IP Token/Authentication works ?](https://devcentral.f5.com/questions/how-big-ip-token-authentication-works-47813) if you request a token, you'll get the same one until the original expires.  Is that true?  If so, there are only 2 options for automating renegotiation:

1. Exception based: attempt a request with the original token, and if it fails request a new one with credentials.  
2. Calculation based: request a new one based on calculated expiration.  Caveat: Potential for errors renegotiating even partial seconds early or late.  Would likely have to fallback on Exception based to be reliable.

IMHO, exception based renegotiation should be implemented in Invoke-RestMethodOverride not Test-F5Session, because Test-F5Session would have to make an extra http request to the F5 to determine the state of the token.  Also, although unlikely, it is possible that Test-F5Session would determine a token is active but that same token expires just prior to a subsequent Invoke-RestMethodOverride call.

**Comment by vercellone** [comment]
Please have a look at my new [tokenrefresh branch](https://github.com/vercellone/POSH-LTM-Rest/tree/tokenrefresh).  In it, I implemented a private Invoke-F5RestMethod function, which simplifies New-F5Session, Invoke-RestMethodOverride, and New-F5Session while providing more flexibility for handling authentication and retries.

I did not implement the token refresh code itself, but I added a TODO: place holder for where I think it belongs.

Let me know what you think.

**Comment by joel74** [comment]
The post I referenced is [here.](https://devcentral.f5.com/questions/how-big-ip-token-authentication-works-47813). Jason, I'll check out the tokenrefresh branch. From a security standpoint, is it okay to always renegotiate the authentication? Another option is to allow a custom expiration / lifespan and simply expire when the time limit is hit. I don't think we should rule that out.

**Comment by vercellone** [comment]
It can be implemented as a sliding expiration that doesn't renegotiate if the session is idle.

**Comment by joel74** [comment]
I like the idea of implementing a private Invoke-F5RestMethod function, and cleaning up the calls to Invoke-RestMethodOverride, but I'm leaning against a sliding expiration or automatic extension of the token's lifespan. I think we should honor's F5 default of 20 minutes with the option to override the lifespan up to the max allowed of 10 hours.

**Comment by joel74** [comment]
See this [commit](https://github.com/joel74/POSH-LTM-Rest/commit/bc241c135bf2112fe39a00c49088b1187979425d)

**Comment by vercellone** [comment]
Your TokenLifespan code looks fine.  

Based on "Auth token shouldn't expire if in use" I thought you wanted an auto renegotiation.  But, I have no objection.

**Comment by joel74** [comment]
I was originally thinking auto-negotiation was the thing to do, before I knew that changing the expiration via a patch was an option. Thanks for reviewing.

**Comment by joel74** [comment]
Closing this issue as resolved. The New-F5Session function now accepts an optional param called TokenLifespan by which a token's life can be extended to the max allowed by iControlREST - 10 hours. Otherwise, the token expires after the default of 20 minutes.
